# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/alpine-wait-for-it"
    schedule:
      interval: "weekly"
    commit-message:
      include: "scope"
      prefix: "docker"
  - package-ecosystem: "docker"
    directory: "/php-8.3-alpine-composer"
    schedule:
      interval: "daily"
    commit-message:
      include: "scope"
      prefix: "docker"
    ignore:
      - dependency-name: "php"
        versions: ["~> 8.4"]
  - package-ecosystem: "docker"
    directory: "/php-8.4-alpine-composer"
    schedule:
      interval: "daily"
    commit-message:
      include: "scope"
      prefix: "docker"
    ignore:
      - dependency-name: "php"
        versions: ["~> 8.5"]

# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
    commit-message:
      include: "scope"
      prefix: "github-actions"
